extends "res://tests/phase_5_weapon_test.gd"

var game: Node3D

func load_menu() -> void:
	if current_scene != null:
		current_scene.queue_free()
		await frames(3)
	var menu: Control = load("res://scenes/main/MainMenu.tscn").instantiate()
	root.add_child(menu)
	current_scene = menu
	await frames(5)

func start_play() -> void:
	await click_scaled(current_scene.play_button)
	await frames(20)
	await wait_for_gameplay()
	game = current_scene
	game.clock.set_process(false)

func run() -> void:
	root.size = Vector2i(1280, 720)
	await load_menu()
	check(Input.mouse_mode == Input.MOUSE_MODE_VISIBLE and not paused, "main menu has free mouse and unpaused tree")
	await capture("phase9_main_menu")
	await click_button(current_scene.help_button)
	await frames(3)
	check(current_scene.guide.visible, "main menu guide opens through actual click")
	await capture("phase9_controls")
	key(KEY_ESCAPE)
	check(not current_scene.guide.visible, "Escape closes guide and returns button focus")
	await start_play()
	check(game.player.health.current_hp == 100 and game.clock.current_day == 1 and not game.debug_controls.active, "Play starts fresh Day1 with hidden debug markers")
	await capture("phase9_day_farm")
	var player: PlayerController = game.player
	# Produce real crafting materials through existing plot interactions and timestamp growth.
	for row in [["seed_lead", 0], ["seed_paper", 1], ["seed_copper", 2]]:
		game.inventory.select_seed(StringName(row[0]))
		var plot: FarmPlot = game.get_node("MainWorld/FarmArea").get_child(row[1])
		player.position = plot.global_position + Vector3(0, 0.05, 1)
		await frames(4)
		key(KEY_E)
		game.clock.advance_game_minutes(60)
		key(KEY_E)
		check(plot.state == FarmPlot.State.EMPTY and game.inventory.has_item(plot._catalog.get_plant(StringName(String(row[0]).trim_prefix("seed_"))).harvest_item.id), "input plants and harvests " + row[0])
	player.position = game.get_node("MainWorld/Workbench").position + Vector3(0, 0.05, 1.1)
	await frames(5)
	key(KEY_E)
	await frames(3)
	await click_button(game.crafting_ui.craft_button)
	check(game.inventory.get_item_amount(&"basic_ammo") == 10, "Workbench UI crafts farmed ammo")
	await capture("phase9_crafting")
	key(KEY_ESCAPE)
	key(KEY_TAB)
	await frames(3)
	check(game.inventory_ui.is_open and paused, "inventory owns input and pause")
	await capture("phase9_inventory")
	key(KEY_ESCAPE)
	key(KEY_ESCAPE)
	await frames(3)
	var clock_before: float = game.clock.get_elapsed_minutes()
	var player_before := player.position
	Input.action_press("move_forward")
	await frames(10)
	Input.action_release("move_forward")
	check(game.pause_menu.is_open and player.position == player_before and game.clock.get_elapsed_minutes() == clock_before and not game.weapons.try_fire(), "pause freezes movement, clock and shooting")
	await capture("phase9_pause")
	await click_button(game.pause_menu.help_button)
	await frames(3)
	check(game.pause_menu.guide.visible, "pause guide opens without resuming")
	await capture("phase9_pause_guide")
	key(KEY_ESCAPE)
	check(game.pause_menu.is_open and not game.pause_menu.guide.visible, "Escape guide returns to pause")
	key(KEY_ESCAPE)
	# Night combat uses the actual rifle, reload and damage receiver.
	player.position = Vector3(12, 0.05, 0)
	await frames(3)
	game.clock.skip_to_night()
	key(KEY_Q)
	key(KEY_R)
	await frames(95)
	var enemy: NormalZombie = game.debug_controls.zombie_spawner.spawn_at(Vector3(12, 0.05, -4))
	mouse(MOUSE_BUTTON_RIGHT, true)
	await frames(10)
	aim_at(player, enemy.position + Vector3.UP)
	var cues_before: int = game.audio.cues_played
	for _shot in 5:
		aim_at(player, enemy.position + Vector3.UP)
		mouse(MOUSE_BUTTON_LEFT, true)
		mouse(MOUSE_BUTTON_LEFT, false)
		await frames(13)
	check(enemy.health.is_dead and game.audio.cues_played >= cues_before + 5, "night combat hits, kills and emits bounded audio cues")
	await capture("phase9_night_combat")
	mouse(MOUSE_BUTTON_RIGHT, false)
	# Rest fade and day transition, isolated from combat balance.
	for _tick in 80:
		game.waves._spawn_wait = 0
		game.waves.debug_kill_active()
		await frames(2)
		if game.waves.state == NightWaveManager.State.CLEARED: break
	check(game.rest.request_rest(player), "cleared wave permits existing rest")
	await frames(10)
	check(game.presentation.overlay.color.a > 0.5 and paused, "rest visibly fades with gameplay paused")
	await frames(45)
	check(game.clock.current_day == 2 and not paused and game.presentation.overlay.color.a == 0, "rest fade returns to morning with controls restored")
	player.health.take_damage(100)
	await frames(3)
	check(game.hud.death_panel.visible and Input.mouse_mode == Input.MOUSE_MODE_VISIBLE, "game-over buttons get free mouse")
	await capture("phase9_game_over")
	await click_button(game.hud.death_panel.find_child("MainMenu", true, false))
	await frames(12)
	check(current_scene.has_method("_close_guide") and not paused, "game-over returns to main menu without stuck pause")
	await start_play()
	game.debug_controls.set_active(true)
	game.debug_controls.execute(&"debug_set_day_10")
	game.debug_controls.set_active(false)
	await frames(3)
	game.clock.seek(10, 17)
	await frames(3)
	check(game.hud.toast_label.text.contains("FINAL NIGHT"), "final-night warning is distinct")
	game.clock.skip_to_night()
	await frames(5)
	check(game.hud._night_title.text.contains("FINAL NIGHT") and game.audio.target_volume == -26, "final night has distinctive HUD and stronger ambience")
	await capture("phase9_final_night")
	game.clock.skip_to_day()
	await frames(3)
	var ending: GamePresentation = game.presentation
	var health_before: float = game.player.health.current_hp
	game.player.health.take_damage(50)
	ending.start_ending()
	game.clock.day_started.emit(11)
	check(ending.ending_started and ending.ending_starts == 1 and game.player.health.current_hp == health_before and not game.player.camera_rig.can_control(), "ending starts once and blocks gameplay/damage")
	await frames(190)
	check(ending.rescue_camera.current and ending.rescue_vehicle.visible and game.waves.tracked.is_empty(), "rescue camera and arriving helicopter visible after threat cleanup")
	await capture("phase9_rescue_arrival")
	await frames(130)
	await capture("phase9_rescue_landed")
	await frames(180)
	check(ending.ending_finished and ending.ending_panel.visible, "sequence reaches ending screen")
	await capture("phase9_ending")
	root.size = Vector2i(1920, 1080)
	await frames(5)
	await capture("phase9_ending_1080")
	check(root.get_visible_rect().encloses(ending.ending_panel.get_global_rect()), "ending panel stays within 1920x1080")
	await click_scaled(ending.ending_panel.find_child("MainMenu", true, false))
	await frames(15)
	check(current_scene.has_method("_close_guide") and not paused and Input.mouse_mode == Input.MOUSE_MODE_VISIBLE, "ending screen returns to usable main menu")
	await capture("phase9_menu_1080")
	await start_play()
	check(game.clock.current_day == 1 and game.progression.unlocked_seed_ids.size() == 5 and game.player.health.damage_enabled, "new play after ending resets day, unlocks and damage gate")
	await capture("phase9_gameplay_1080")
	game.waves.debug_set_day(10)
	game.clock.skip_to_night()
	game.player.health.take_damage(100)
	game.clock.skip_to_day()
	check(not game.presentation.ending_started and game.waves.state == NightWaveManager.State.GAME_OVER, "death on final night cannot trigger rescue")
	await frames(3)
	await click_scaled(game.hud.death_panel.find_child("Restart", true, false))
	await frames(20)
	await wait_for_gameplay()
	game = current_scene
	game.clock.set_process(false)
	game.waves.debug_set_day(10)
	game.clock.skip_to_night()
	game.clock.skip_to_day()
	await frames(500)
	await click_scaled(game.presentation.ending_panel.find_child("PlayAgain", true, false))
	await frames(20)
	await wait_for_gameplay()
	game = current_scene
	check(game.clock.current_day == 1 and not game.presentation.ending_started, "ending Play Again button restarts cleanly")
	key(KEY_ESCAPE)
	await frames(3)
	await click_scaled(game.pause_menu.get_node("Screen/Panel/Rows/Restart"))
	await frames(20)
	await wait_for_gameplay()
	game = current_scene
	check(not paused and game.clock.current_day == 1, "pause Restart releases pause and resets campaign")
	key(KEY_ESCAPE)
	await frames(3)
	await click_scaled(game.pause_menu.get_node("Screen/Panel/Rows/MainMenu"))
	await frames(15)
	check(current_scene.has_method("_close_guide") and not paused, "pause Main Menu returns safely")
	print("PHASE_9_PRESENTATION_RESULT failures=", failures)
	current_scene.queue_free()
	await frames(5)
	quit(1 if failures else 0)



func click_scaled(button: Button) -> void:
	var point := root.get_final_transform() * button.get_global_rect().get_center()
	for down in [true, false]:
		var event := InputEventMouseButton.new()
		event.button_index = MOUSE_BUTTON_LEFT
		event.position = point
		event.global_position = point
		event.pressed = down
		root.push_input(event)
