extends "res://tests/special_ammo_test.gd"

func quantities() -> Dictionary:
	var result := {}
	for slot in bag.get_slots(): result[slot.item.id] = bag.get_item_amount(slot.item.id)
	return result

func run() -> void:
	root.size = Vector2i(1280,720)
	await new_game()
	key(KEY_Q)
	check(not weapons.cycle_ammo() and rifle.selected_ammo_type == rifle.data.ammo_type, "no owned ammo leaves default selection unchanged")
	check(not game.hud._equipment_hint.text.contains("SWITCH AMMO"), "no special ammo hides contextual hint")
	check(not weapons.start_reload() and rifle.current_magazine == 0, "zero reserve reload never creates rounds")
	var fire_only: ItemData = game.catalog.get_item(&"fire_ammo")
	bag.add_item(fire_only,2)
	check(game.hud._equipment_hint.text.contains("SWITCH AMMO"), "only Fire owned still shows first selector hint")
	key(KEY_C)
	await frames(100)
	check(rifle.selected_ammo_type == fire_only and rifle.magazine_ammo_type == fire_only and rifle.current_magazine == 2, "Fire can be selected and loaded without any Normal reserve or magazine")
	await new_game()
	key(KEY_Q)
	for slot in bag.get_slots():
		if slot.item.item_type != ItemData.ItemType.WEAPON: bag.remove_item(slot.item.id,bag.get_item_amount(slot.item.id))
	var normal: ItemData = game.catalog.get_item(&"basic_ammo")
	var fire: ItemData = game.catalog.get_item(&"fire_ammo")
	bag.add_item(normal,3)
	key(KEY_R)
	await frames(100)
	check(rifle.current_magazine == 3 and weapons.reserve_ammo() == 0 and not weapons.start_reload(), "partial Normal reload takes only three owned rounds")
	bag.add_item(fire,11)
	bag.capacity = bag.get_slots().size()
	var before := quantities()
	key(KEY_C)
	check(rifle.selected_ammo_type == fire and not rifle.is_reloading and game.hud.toast_label.text.contains("Bag full"), "full bag refuses swap when old ammo has nowhere to return")
	check(quantities() == before and rifle.current_magazine == 3 and rifle.magazine_ammo_type == normal, "failed swap preserves every inventory quantity and loaded round")
	bag.capacity += 1
	key(KEY_R)
	await frames(20)
	game.equipment.cycle_weapon(1)
	check(not rifle.is_reloading and rifle.reload_ammo_type == null and quantities() == before, "weapon change cancels reload snapshot without deductions")
	game.equipment.cycle_weapon(1)
	check(rifle.selected_ammo_type == fire and rifle.magazine_ammo_type == normal and rifle.current_magazine == 3, "cancelled swap retains distinct selected and loaded state")
	# Capacity can change during a timed reload. Commit must revalidate atomically.
	key(KEY_R)
	await frames(20)
	var filler := ItemData.new()
	filler.id = &"test_filler"
	filler.display_name = "Test filler"
	filler.max_stack = 1
	check(bag.add_item(filler), "fixture fills remaining space during reload")
	before = quantities()
	await frames(80)
	check(not rifle.is_reloading and rifle.current_magazine == 3 and rifle.magazine_ammo_type == normal and quantities() == before, "commit rejects changed capacity with no ammo loss or mixed magazine")
	bag.remove_item(filler.id,1)
	key(KEY_R)
	await frames(100)
	check(rifle.magazine_ammo_type == fire and rifle.current_magazine == 10 and bag.get_item_amount(fire.id) == 1 and bag.get_item_amount(normal.id) == 3, "successful swap conserves all fourteen rounds")
	check(not weapons.cycle_ammo() or rifle.selected_ammo_type == normal, "available cycling only visits owned/loaded compatible ammo")
	if rifle.is_reloading:
		key(KEY_ESCAPE)
		key(KEY_ESCAPE)
	# Loaded Fire must remain the shot source even after selecting Normal and cancelling.
	check(rifle.magazine_ammo_type == fire, "cancel keeps loaded Fire")
	var enemy := await target_zombie()
	await fire_at(enemy, fire)
	check(rifle.current_magazine == 9, "shot after cancelled selection still uses Fire magazine")
	rifle.selected_ammo_type = fire
	key(KEY_R)
	await frames(100)
	check(rifle.current_magazine == 10 and bag.get_item_amount(fire.id) == 0 and bag.get_item_amount(normal.id) == 3, "same-type top-up spends exactly one Fire reserve and no Normal")
	enemy = await target_zombie()
	for _i in 10:
		aim_at(player,enemy.global_position + Vector3.UP)
		check(weapons.try_fire(), "real shot spends remaining Fire")
		await frames(13)
	check(rifle.current_magazine == 0 and not weapons.try_fire() and rifle.selected_ammo_type == fire, "exhaustion does not silently change ammo or allow negative magazine")
	key(KEY_R)
	check(rifle.selected_ammo_type == normal and game.hud.toast_label.text == "Switched to Basic Ammo", "R announces fallback before partial Normal reload")
	await frames(100)
	check(rifle.current_magazine == 3 and bag.get_item_amount(normal.id) == 0 and bag.get_item_amount(fire.id) == 0, "fallback consumes only three available Normal rounds")
	enemy.despawn()
	await frames(3)
	# Missing target reserve at commit cannot replace the old magazine with free ammo.
	bag.capacity = 24
	bag.add_item(fire,10)
	key(KEY_C)
	await frames(20)
	bag.remove_item(fire.id,10)
	await frames(80)
	check(rifle.current_magazine == 3 and rifle.magazine_ammo_type == normal and bag.get_item_amount(fire.id) == 0, "reserve disappearing during reload leaves loaded ammo intact")
	bag.add_item(fire,10)
	key(KEY_R)
	await frames(20)
	before = quantities()
	player.health.die()
	check(not rifle.is_reloading and quantities() == before and rifle.current_magazine == 3, "death cancels swap without transferring inventory")
	await new_game()
	var ice: ItemData = game.catalog.get_item(&"ice_ammo")
	var poison: ItemData = game.catalog.get_item(&"poison_ammo")
	enemy = await target_zombie()
	enemy.apply_ammo_effect(fire)
	enemy.apply_ammo_effect(ice)
	enemy.apply_ammo_effect(poison)
	check(enemy.ammo_effects.size() == 3 and enemy.ammo_speed_multiplier() == 0.5, "different statuses coexist with one timer each")
	var hp := enemy.health.current_hp
	enemy._tick_ammo_effects(10.0)
	check(is_equal_approx(enemy.health.current_hp,hp - 25.0) and enemy.ammo_effects.is_empty(), "long frame clamps burn/poison to nine plus sixteen damage")
	for rate in [30,120]:
		enemy.health.reset()
		enemy.apply_ammo_effect(poison)
		for _i in rate * 5: enemy._tick_ammo_effects(1.0 / rate)
		check(is_equal_approx(enemy.health.current_hp,984.0) and enemy.ammo_effects.is_empty(), "Poison total damage agrees at %d Hz" % rate)
	enemy.despawn()
	await frames(3)
	var invalid := rifle.data.duplicate() as WeaponData
	invalid.compatible_ammo_types = rifle.data.compatible_ammo_types.duplicate()
	invalid.compatible_ammo_types.append(game.catalog.get_item(&"lead"))
	check(not invalid.validation_errors().is_empty(), "compatibility rejects non-ammo resources")
	invalid = rifle.data.duplicate() as WeaponData
	invalid.compatible_ammo_types = rifle.data.compatible_ammo_types.duplicate()
	invalid.compatible_ammo_types.append(fire)
	check(not invalid.validation_errors().is_empty(), "compatibility rejects duplicate ammo IDs")
	var melee := load("res://resources/weapons/wooden_bat.tres").duplicate() as WeaponData
	melee.compatible_ammo_types = melee.compatible_ammo_types.duplicate()
	melee.compatible_ammo_types.append(fire)
	check(not melee.validation_errors().is_empty(), "melee definition rejects any compatible ammo")
	await new_game()
	key(KEY_Q)
	for slot in bag.get_slots():
		if slot.item.item_type != ItemData.ItemType.WEAPON: bag.remove_item(slot.item.id,bag.get_item_amount(slot.item.id))
	bag.add_item(normal,3)
	key(KEY_R)
	await frames(100)
	bag.add_item(fire,10)
	bag.capacity = bag.get_slots().size()
	key(KEY_C)
	await frames(100)
	check(rifle.magazine_ammo_type == fire and rifle.current_magazine == 10 and bag.get_item_amount(normal.id) == 3 and bag.get_item_amount(fire.id) == 0, "full bag swap succeeds when consuming the entire target stack frees a return slot")
	print("SPECIAL_AMMO_EDGE_RESULT failures=",failures)
	game.queue_free()
	await frames(3)
	quit(failures)
