extends "res://tests/phase_9_presentation_test.gd"
## Same current scene/input route before and after the UI pass; controlled fixtures.

func run() -> void:
	if not capture_directory.is_empty(): DirAccess.make_dir_recursive_absolute(capture_directory)
	root.size = Vector2i(1280,720)
	await load_menu()
	await capture("01_main_menu")
	var button_point: Vector2 = root.get_final_transform() * current_scene.help_button.get_global_rect().get_center()
	var hover := InputEventMouseMotion.new()
	hover.position = button_point
	hover.global_position = button_point
	root.push_input(hover)
	await frames(10)
	await capture("30_menu_hover")
	var press := InputEventMouseButton.new()
	press.button_index = MOUSE_BUTTON_LEFT
	press.position = button_point
	press.global_position = button_point
	press.pressed = true
	root.push_input(press)
	await frames(3)
	await capture("31_menu_pressed")
	press.pressed = false
	root.push_input(press)
	await frames(10)
	if current_scene.guide.visible: key(KEY_ESCAPE)
	await click_scaled(current_scene.settings_button)
	await frames(15)
	check(current_scene.settings.visible, "main Settings opens through actual click")
	await capture("28_main_settings")
	key(KEY_ESCAPE)
	await click_scaled(current_scene.help_button)
	await frames(15)
	check(current_scene.guide.visible,"main menu guide opens")
	await capture("02_guide")
	key(KEY_ESCAPE)
	await start_play()
	await frames(20)
	check(not game.debug_controls.active,"normal play hides developer controls")
	await capture("03_farming_hud")
	key(KEY_TAB)
	await frames(15)
	check(game.inventory_ui.is_open and paused,"bag opens and pauses through Tab")
	await capture("04_inventory")
	key(KEY_ESCAPE)
	for index in 3:
		var id: StringName = [&"seed_lead",&"seed_paper",&"seed_copper"][index]
		game.inventory.select_seed(id)
		var plot: FarmPlot = game.get_node("MainWorld/FarmArea").get_child(index)
		await face_interaction(plot)
		if index == 0: await capture("05_plant_prompt")
		key(KEY_E)
		await frames(4)
		check(plot.state == FarmPlot.State.PLANTED,"actual E plants "+String(id))
		game.clock.advance_game_minutes(10)
		if index == 0: await capture("06_growing_prompt")
		game.clock.advance_game_minutes(60)
		if index == 0: await capture("07_harvest_prompt")
		key(KEY_E)
		await frames(4)
		check(plot.state == FarmPlot.State.EMPTY,"actual E harvests "+String(id))
	await face_interaction(game.get_node("MainWorld/Workbench"))
	await capture("08_workbench_prompt")
	key(KEY_E)
	await frames(15)
	check(game.crafting_ui.is_open,"actual E opens Workbench")
	await capture("09_crafting_ready")
	await click_scaled(game.crafting_ui.craft_button)
	await frames(15)
	check(game.inventory.get_item_amount(&"basic_ammo")==10,"actual craft button produces10 ammo")
	await capture("10_crafting_success")
	var recipes: Array = game.crafting_system.get_recipes()
	await click_scaled(game.crafting_ui._buttons[recipes.back()])
	await frames(15)
	check(game.crafting_ui.craft_button.disabled,"locked recipe cannot craft")
	await capture("11_crafting_locked")
	key(KEY_ESCAPE)
	key(KEY_TAB)
	await frames(15)
	await capture("12_inventory_materials")
	key(KEY_ESCAPE)
	key(KEY_ESCAPE)
	await frames(15)
	check(game.pause_menu.is_open,"pause opens through Escape")
	await capture("13_pause")
	await click_scaled(game.pause_menu.settings_button)
	await frames(15)
	check(game.pause_menu.settings.visible and paused, "pause Settings retains pause ownership")
	await capture("29_pause_settings")
	key(KEY_ESCAPE)
	await click_scaled(game.pause_menu.help_button)
	await frames(15)
	await capture("14_pause_guide")
	key(KEY_ESCAPE)
	key(KEY_ESCAPE)
	game.clock.skip_to_night()
	for _tick in 100:
		game.waves._spawn_wait = 0
		game.waves.debug_kill_active()
		await frames(2)
		if game.waves.state == NightWaveManager.State.CLEARED: break
	await frames(3)
	key(KEY_N)
	await frames(15)
	check(game.skip_day.is_open,"N opens confirmation")
	await capture("15_wait_confirmation")
	key(KEY_ESCAPE)
	game.waves.debug_set_day(1)
	key(KEY_Q)
	await frames(15)
	await capture("16_rifle_hud")
	key(KEY_R)
	await frames(20)
	await capture("17_reload_hud")
	await frames(80)
	check(game.weapons.current.current_magazine==10,"reload keeps actual magazine accounting")
	mouse(MOUSE_BUTTON_RIGHT,true)
	await frames(15)
	await capture("18_aim_hud")
	mouse(MOUSE_BUTTON_LEFT,true)
	mouse(MOUSE_BUTTON_LEFT,false)
	await frames(2)
	check(game.weapons.current.current_magazine==9,"actual shooting consumes one round")
	game.hud.get_node("Root/Crosshair").flash_hit()
	await capture("19_hit_feedback")
	mouse(MOUSE_BUTTON_RIGHT,false)
	mouse(MOUSE_BUTTON_WHEEL_DOWN,true)
	mouse(MOUSE_BUTTON_WHEEL_DOWN,false)
	await frames(15)
	check(game.weapons.current.data.is_melee(),"actual wheel selects bat")
	await capture("20_bat_hud")
	mouse(MOUSE_BUTTON_LEFT,true)
	mouse(MOUSE_BUTTON_LEFT,false)
	await frames(3)
	check(game.weapons.current.is_swinging,"bat still swings through LMB")
	await capture("21_bat_swing")
	game.player.health.take_damage(20)
	await capture("22_damage_feedback")
	game.clock.skip_to_night()
	await frames(20)
	await capture("23_night_hud")
	for tick in 100:
		game.waves._spawn_wait=0
		game.waves.debug_kill_active()
		await frames(2)
		if game.waves.state==NightWaveManager.State.CLEARED: break
	key(KEY_Q)
	await face_interaction(game.get_node("MainWorld/Bed"))
	await capture("24_rest_prompt")
	if "--all-resolutions" in OS.get_cmdline_user_args():
		await resolution_views()
		await edge_views()
	game.player.health.take_damage(100)
	await frames(15)
	check(game.hud.death_panel.visible,"death menu displays")
	await capture("25_game_over")
	await click_scaled(game.hud.death_panel.find_child("MainMenu",true,false))
	await frames(15)
	await start_play()
	game.clock.seek(10,18)
	await frames(10)
	await capture("26_final_night")
	game.clock.skip_to_day()
	await frames(500)
	check(game.presentation.ending_finished,"existing ending reaches menu")
	await capture("27_ending")
	if "--all-resolutions" in OS.get_cmdline_user_args(): await menu_resolutions()
	print("UI_POLISH_CAPTURE_RESULT failures=",failures)
	quit(1 if failures else 0)

func face_interaction(target: Interactable) -> void:
	game.player.position=target.global_position+Vector3(0,0.25,1.35)
	game.player.velocity=Vector3.ZERO
	game.player.camera_rig.rotation.y=0
	await frames(20)
	check(game.player.interactor.target==target,"interaction target acquired: "+target.name)

func resolution_views() -> void:
	for dimensions in [Vector2i(960,540),Vector2i(1920,1080),Vector2i(1024,768)]:
		root.size=dimensions
		await frames(15)
		var suffix := "_%dx%d"%[dimensions.x,dimensions.y]
		await capture("responsive_hud"+suffix)
		key(KEY_TAB)
		await frames(15)
		await capture("responsive_inventory"+suffix)
		key(KEY_ESCAPE)
		game.crafting_ui.set_open(true)
		await frames(15)
		await capture("responsive_crafting"+suffix)
		key(KEY_ESCAPE)
		key(KEY_ESCAPE)
		await frames(15)
		await capture("responsive_pause"+suffix)
		await click_scaled(game.pause_menu.settings_button)
		await frames(15)
		await capture("responsive_pause_settings"+suffix)
		key(KEY_ESCAPE)
		key(KEY_ESCAPE)
	root.size=Vector2i(1280,720)
	await frames(10)


func edge_views() -> void:
	key(KEY_TAB)
	await frames(15)
	var slots: Array = game.inventory.get_slots()
	for index in slots.size():
		if slots[index].item.id == &"wooden_bat":
			await click_scaled(game.inventory_ui.slot_buttons[index])
			await frames(15)
			await capture("edge_weapon_selection")
		if slots[index].item.id == &"lead":
			await click_scaled(game.inventory_ui.slot_buttons[index])
			await frames(15)
			await capture("edge_material_selection")
	key(KEY_ESCAPE)
	game.inventory.clear()
	for id in [&"lead",&"paper",&"copper"]: game.inventory.add_item(game.catalog.get_item(id),3)
	game.inventory.capacity=3
	game.crafting_ui._select_recipe(game.crafting_system.get_recipes()[0])
	game.crafting_ui.set_open(true)
	await frames(15)
	await capture("edge_crafting_full_bag")
	game.inventory.capacity=24
	game.inventory.remove_item(&"copper",3)
	game.crafting_ui.refresh()
	await frames(15)
	await capture("edge_crafting_missing_material")
	game.crafting_ui.set_open(false)
	game.inventory.clear()
	key(KEY_TAB)
	await frames(15)
	await capture("edge_empty_bag")
	key(KEY_ESCAPE)
	game.player.health.take_damage(60)
	await frames(15)
	await capture("edge_low_health_empty_seed")

func menu_resolutions() -> void:
	await click_scaled(game.presentation.ending_panel.find_child("MainMenu",true,false))
	await frames(15)
	for dimensions in [Vector2i(960,540),Vector2i(1920,1080),Vector2i(1024,768)]:
		root.size=dimensions
		await frames(15)
		var suffix := "_%dx%d"%[dimensions.x,dimensions.y]
		await capture("responsive_menu"+suffix)
		await click_scaled(current_scene.help_button)
		await frames(15)
		await capture("responsive_guide"+suffix)
		key(KEY_ESCAPE)
		await click_scaled(current_scene.settings_button)
		await frames(15)
		await capture("responsive_settings"+suffix)
		key(KEY_ESCAPE)


func capture(label: String) -> void:
	await frames(2)
	var candidates: Array[Control] = []
	if is_instance_valid(game) and current_scene == game:
		for panel: Control in [game.hud._clock_panel,game.hud._stats_panel,game.hud._equipment_panel,game.hud._wave_panel,game.hud.prompt_panel,game.inventory_ui._panel,game.crafting_ui._panel,game.pause_menu.get_node("Screen/Panel"),game.hud.death_panel]:
			if panel.is_visible_in_tree(): candidates.append(panel)
		if game.skip_day.is_open: candidates.append(game.skip_day.screen.find_child("Confirmation",true,false))
		if game.presentation.ending_finished: candidates.append(game.presentation.ending_panel)
		if game.pause_menu.settings.visible: candidates.append(game.pause_menu.settings)
	elif current_scene != null and current_scene.get("guide") != null:
		if current_scene.guide.visible: candidates.append(current_scene.guide)
		if current_scene.settings.visible: candidates.append(current_scene.settings)
	for panel in candidates:
		var rectangle := panel.get_global_rect()
		var transform := root.get_final_transform()
		var start := transform * rectangle.position
		var end := transform * rectangle.end
		print("UI_RECT ",label,"/",panel.name," pixels=",start,"..",end," window=",root.size)
		check(start.x >= -1 and start.y >= -1 and end.x <= root.size.x+1 and end.y <= root.size.y+1,"layout fits viewport: "+label+"/"+panel.name)
	await super.capture(label)
