class_name EnvironmentAssets
extends RefCounted

const SCENES := {
	"Cabin": preload("res://Asset/Cabin.glb"),
	"Barrel": preload("res://Asset/Post Apocolypse Pack.undefined-glb/Barrel.glb"),
	"Chest": preload("res://Asset/Post Apocolypse Pack.undefined-glb/Chest.glb"),
	"Chest-RfSBvgcZUD": preload("res://Asset/Post Apocolypse Pack.undefined-glb/Chest-RfSBvgcZUD.glb"),
	"Pallet": preload("res://Asset/Post Apocolypse Pack.undefined-glb/Pallet.glb"),
	"Pallet Broken": preload("res://Asset/Post Apocolypse Pack.undefined-glb/Pallet Broken.glb"),
	"Water Tower": preload("res://Asset/Post Apocolypse Pack.undefined-glb/Water Tower.glb"),
	"Container Green": preload("res://Asset/Post Apocolypse Pack.undefined-glb/Container Green.glb"),
	"Container Red": preload("res://Asset/Post Apocolypse Pack.undefined-glb/Container Red.glb"),
	"Pipes": preload("res://Asset/Post Apocolypse Pack.undefined-glb/Pipes.glb"),
	"Cinder Block": preload("res://Asset/Post Apocolypse Pack.undefined-glb/Cinder Block.glb"),
	"Damaged Couch": preload("res://Asset/Post Apocolypse Pack.undefined-glb/Damaged Couch.glb"),
	"Trash Bag": preload("res://Asset/Post Apocolypse Pack.undefined-glb/Trash Bag.glb"),
	"Trash Bags": preload("res://Asset/Post Apocolypse Pack.undefined-glb/Trash Bags.glb"),
	"Wheel": preload("res://Asset/Post Apocolypse Pack.undefined-glb/Wheel.glb"),
	"Wheels Stack": preload("res://Asset/Post Apocolypse Pack.undefined-glb/Wheels Stack.glb"),
	"Traffic Barrier": preload("res://Asset/Post Apocolypse Pack.undefined-glb/Traffic Barrier.glb"),
	"Traffic Cone": preload("res://Asset/Post Apocolypse Pack.undefined-glb/Traffic Cone.glb"),
	"Fire Hydrant": preload("res://Asset/Post Apocolypse Pack.undefined-glb/Fire Hydrant.glb"),
	"Tree": preload("res://Asset/Stylized Nature MegaKit.undefined-glb/Tree.glb"),
	"Tree-qZtx0AHhcy": preload("res://Asset/Stylized Nature MegaKit.undefined-glb/Tree-qZtx0AHhcy.glb"),
	"Tree-aVOxaHRPWe": preload("res://Asset/Stylized Nature MegaKit.undefined-glb/Tree-aVOxaHRPWe.glb"),
	"Tree-QVOop92WmG": preload("res://Asset/Stylized Nature MegaKit.undefined-glb/Tree-QVOop92WmG.glb"),
	"Pine": preload("res://Asset/Stylized Nature MegaKit.undefined-glb/Pine.glb"),
	"Pine-699sFuLCN2": preload("res://Asset/Stylized Nature MegaKit.undefined-glb/Pine-699sFuLCN2.glb"),
	"Pine-79gmlLnweB": preload("res://Asset/Stylized Nature MegaKit.undefined-glb/Pine-79gmlLnweB.glb"),
	"Dead Tree": preload("res://Asset/Stylized Nature MegaKit.undefined-glb/Dead Tree.glb"),
	"Dead Tree-Mcd2zYqyww": preload("res://Asset/Stylized Nature MegaKit.undefined-glb/Dead Tree-Mcd2zYqyww.glb"),
	"Rock Medium": preload("res://Asset/Stylized Nature MegaKit.undefined-glb/Rock Medium.glb"),
	"Rock Medium-JQxF95498B": preload("res://Asset/Stylized Nature MegaKit.undefined-glb/Rock Medium-JQxF95498B.glb"),
	"Rock Medium-s1OJ3bBzqc": preload("res://Asset/Stylized Nature MegaKit.undefined-glb/Rock Medium-s1OJ3bBzqc.glb"),
	"Pebble Round": preload("res://Asset/Stylized Nature MegaKit.undefined-glb/Pebble Round.glb"),
	"Pebble Square": preload("res://Asset/Stylized Nature MegaKit.undefined-glb/Pebble Square.glb"),
	"Bush with Flowers": preload("res://Asset/Stylized Nature MegaKit.undefined-glb/Bush with Flowers.glb"),
	"Bush": preload("res://Asset/Stylized Nature MegaKit.undefined-glb/Bush.glb"),
	"Fern": preload("res://Asset/Stylized Nature MegaKit.undefined-glb/Fern.glb"),
	"Grass": preload("res://Asset/Stylized Nature MegaKit.undefined-glb/Grass.glb"),
	"Grass Wispy": preload("res://Asset/Stylized Nature MegaKit.undefined-glb/Grass Wispy.glb"),
	"Tall Grass": preload("res://Asset/Stylized Nature MegaKit.undefined-glb/Tall Grass.glb"),
	"Clover": preload("res://Asset/Stylized Nature MegaKit.undefined-glb/Clover.glb"),
	"Mushroom": preload("res://Asset/Stylized Nature MegaKit.undefined-glb/Mushroom.glb"),
	"Flower Group": preload("res://Asset/Stylized Nature MegaKit.undefined-glb/Flower Group.glb"),
	"Survival_Tent": preload("res://Asset/Survival Pack-glb/Tent.glb"),
	"Survival_Wood Log": preload("res://Asset/Survival Pack-glb/Wood Log.glb"),
	"Survival_Shovel": preload("res://Asset/Survival Pack-glb/Shovel.glb"),
	"Survival_Axe": preload("res://Asset/Survival Pack-glb/Axe.glb"),
	"Survival_Gas Can": preload("res://Asset/Survival Pack-glb/Gas Can.glb"),
	"Survival_Propane Tank": preload("res://Asset/Survival Pack-glb/Propane Tank.glb"),
	"Survival_Radio": preload("res://Asset/Survival Pack-glb/Radio.glb"),
	"Survival_First Aid Kit": preload("res://Asset/Survival Pack-glb/First Aid Kit.glb"),
	"Survival_Can": preload("res://Asset/Survival Pack-glb/Can.glb"),
	"Survival_Can Broken": preload("res://Asset/Survival Pack-glb/Can Broken.glb"),
	"Survival_Bonfire": preload("res://Asset/Survival Pack-glb/Bonfire.glb"),
	"Truck": preload("res://Asset/Low Poly Military Vehicles-glb/Truck.glb"),
	"Jeep": preload("res://Asset/Low Poly Military Vehicles-glb/Jeep.glb"),
	"Ambulance Car": preload("res://Asset/Low Poly Military Vehicles-glb/Ambulance Car.glb"),
}
